### ISSUE TITLE
Feature request: download files from script directory

### ISSUE THREAD

**Issue by atuyosi** [zdenop/tessdata_downloader#1]
Thanks for nice utility.

Could you please add feature to download files from script directory?

- tessdata_best/script
- tessdata_fast/script

Such like Latin.tessdata and etc.

**Comment by zdenop** [comment]
I have it on my TODO list.

**Comment by zdenop** [comment]
done 62ff7bf060a2a07874337a544b676d6c3d251ea7.
This should works:
`tessdata_downloader.py -r tessdata_best -U user:password -x host:port -l script/Latin -t "4.0.0"`
