### ISSUE TITLE
Exception when downloading Spanish trained model

### ISSUE THREAD

**Issue by cmeneses1** [zdenop/tessdata_downloader#2]
Hello,

I get the exception shown in the attached figure when trying to download the Spanish trained model. What can I do?

Thank you in advance.

![Captura de pantalla de 2021-09-16 22-21-21](https://user-images.githubusercontent.com/77629648/133680796-78c60b95-ff2a-4384-a588-5ca1a023a998.png)

**Comment by zdenop** [comment]
screenshot shows that use are using vietOCR - how it is related to this project?

**Comment by cmeneses1** [comment]
Sorry, wrong github project. I's my fault.
